---
- name: Generate account key
  openssl_privatekey:
    path: /etc/ssl/private/acme_account.pem
    mode: u=rw,g-rwx,o-rwx

- name: Generate CSR private key
  openssl_privatekey:
    path: /etc/ssl/private/acme_csr_key.pem
    mode: u=rw,g-rwx,o-rwx

- name: Default cert signing request
  openssl_csr:
    path: /root/acme.csr
    privatekey_path: /etc/ssl/private/acme_csr_key.pem
    subject_alt_name: "{{sites | map(attribute='host') | map('regex_replace', '^', 'DNS:') | list}}"

- name: Check Cert
  acme_certificate:
    account_email: "{{acme_account_email}}"
    account_key_src: /etc/ssl/private/acme_account.pem
    acme_directory: "{{acme_directory}}"
    challenge: http-01
    csr: /root/acme.csr
    dest: /etc/ssl/certs/acme.pem
    acme_version: 2
    terms_agreed: yes
  register: acme_challenge

- name: Fufill challenges
  when: acme_challenge is changed
  block:
  - name: Ensure acme-challenge dir exists
    file:
      path: /var/www/html/.well-known/acme-challenge
      state: directory
  - name: Put the challenge data in www root
    with_dict: "{{ acme_challenge.challenge_data }}"
    copy:
      content: "{{item.value['http-01']['resource_value']}}"
      dest: "/var/www/html/{{item.value['http-01']['resource']}}"
  - name: Configure nginx to serve the challenge response
    copy:
      src: acme_verify.conf
      dest: /etc/nginx/nginx.conf
  - name: Restart nginx
    service:
      name: nginx
      state: restarted

- name: Verify and install the cert
  acme_certificate:
    account_email: "{{acme_account_email}}"
    account_key_src: /etc/ssl/private/acme_account.pem
    acme_directory: "{{acme_directory}}"
    challenge: http-01
    csr: /root/acme.csr
    dest: /etc/ssl/certs/acme.pem
    data: "{{acme_challenge}}"
    acme_version: 2
    terms_agreed: yes