---
- name: Load OS Variables
  include_vars: "{{ansible_distribution}}.yml"

- name: Install nginx
  notify: Restart nginx
  package:
    name: "{{nginx_package}}"
    state: latest

- name: Ensure nginx is started
  service:
    name: nginx
    enabled: yes
    state: started

- name: Install SSL Certificate
  include: certs.yml

- name: Nginx base config
  notify: Restart nginx
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf

- name: Ensure /etc/nginx/conf.d/ exists
  file:
    path: /etc/nginx/conf.d/
    state: directory

- name: Configure http
  notify: Restart nginx
  copy:
    src: default.conf
    dest: /etc/nginx/conf.d/default.conf

- name: Setup Backends
  notify: Restart nginx
  template:
    src: backends.conf.j2
    dest: /etc/nginx/conf.d/backends.conf

- name: Setup Hosts
  notify: Restart nginx
  template:
    src: hosts.conf.j2
    dest: /etc/nginx/conf.d/hosts.conf

