---
- name: Install nginx
  package:
    name: nginx
    state: latest

- name: Nginx base config
  copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf

- name: Configure http
  copy:
    src: default.conf
    dest: /etc/nginx/conf.d/default.conf
